// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXP-jluYDVXEO9yQGFfdxZFAJlx_LUn0I',
    appId: '1:502402706261:web:e56a1719cbd07450a49ddc',
    messagingSenderId: '502402706261',
    projectId: 'bootcampflutter-72a2a',
    authDomain: 'bootcampflutter-72a2a.firebaseapp.com',
    storageBucket: 'bootcampflutter-72a2a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8waUay-aDDRKOb9kZv9vzIH59C5_FIDU',
    appId: '1:502402706261:android:bb43d7a3bc19e2a2a49ddc',
    messagingSenderId: '502402706261',
    projectId: 'bootcampflutter-72a2a',
    storageBucket: 'bootcampflutter-72a2a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMTX6IAQb0akxWqe9S1jCS2eaIlSJuq9E',
    appId: '1:502402706261:ios:ee6b4af7cef357d7a49ddc',
    messagingSenderId: '502402706261',
    projectId: 'bootcampflutter-72a2a',
    storageBucket: 'bootcampflutter-72a2a.firebasestorage.app',
    iosBundleId: 'com.example.bootcampFlutterTm06',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMTX6IAQb0akxWqe9S1jCS2eaIlSJuq9E',
    appId: '1:502402706261:ios:ee6b4af7cef357d7a49ddc',
    messagingSenderId: '502402706261',
    projectId: 'bootcampflutter-72a2a',
    storageBucket: 'bootcampflutter-72a2a.firebasestorage.app',
    iosBundleId: 'com.example.bootcampFlutterTm06',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXP-jluYDVXEO9yQGFfdxZFAJlx_LUn0I',
    appId: '1:502402706261:web:94d51ab166591781a49ddc',
    messagingSenderId: '502402706261',
    projectId: 'bootcampflutter-72a2a',
    authDomain: 'bootcampflutter-72a2a.firebaseapp.com',
    storageBucket: 'bootcampflutter-72a2a.firebasestorage.app',
  );

}